### PR TITLE
Added country, continent, id to GET/org/id

### LINKED ISSUE #140: API: GET /organizations/{id} add `country` to response
{
  country: [where this organization belong]
}

The rule to calculate the country: find the first tree planted by this organization, find the country by the trees coordinates. 

All these functions has been created, so here we just need to compose them and get the result.

### PR DESCRIPTION
**Pull request by mayankbucha**
resolves #140

### CODE REVIEW

**Comment by mayankbucha** [comment]
@dadiorchen an organization can have planter from different countries, therefore trees from different countries also. In this case what should we do? Currently I have joined `entity.id` to `planter.organization_id` and `trees.planter_id` to `planter.id`. But in the above case this will not work.

**Comment by dadiorchen** [comment]
I see, but crossing country org is a rare case, as far as I know there are some orgs crossing countries, but they are not valid data, just for test I think, so for now ,we can just simply get any tree by that org, and assign the country of that tree to the org.

**Comment by dadiorchen** [comment]
By the way, I am looking into your branch that return duplicated records, will let you know my progress.

**Comment by dadiorchen** [comment]
@mayankbucha this is `join the first line` useful for you? by this way, we can just pick the first planter/tree in the org and calculate the country:
https://github.com/Greenstand/treetracker-query-api/pull/212

**Comment by mayankbucha** [comment]
@dadiorchen I updated the relation to join entity to tree directly. I feel the query bit slow, as it was taking a bit on time on my end.

**Pull request merged**
