### PR TITLE
Fix: 404 error returned for unknown trees and countries

### PR DESCRIPTION
**Pull request by kparikh9**
#36

Made change to `HttpError` class - inheriting from Error class breaks the prototype chain and sets the class of `HttpError` objects as `Error`, which breaks the `if (err instanceof HttpError)` check in the `errorHandler` function in `server/routers/utils.ts`. More info can be found [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html#example).

Added test to test 404 check.

Ran into an issue with `knex.ts` in `server/infra/database` not properly reading `.env` file for `DATABASE_URL` value - added `import 'dotenv/config'` to file in order to set up connection to DB, but it wasn't added to this PR.

### CODE REVIEW

**Comment by dadiorchen** [comment]
nice @kparikh9 ! oh, can you resolve the conflict?

**Comment by kparikh9** [comment]
@dadiorchen I believe the linter removes the `next` keyword from the `errorHandler` in the `utils.ts` function since it is not used. However, it is necessary to have because express will use its default handler when the `next` parameter is passed, if it is not errors are not properly caught. Here is some more info: https://expressjs.com/en/guide/error-handling.html.
image

This fails the GitHub Action Pipeline due to ignoring linting. [This discussion](https://github.com/expressjs/generator/issues/78#issuecomment-103152636) eventually links to another ticket where [someone suggests](https://github.com/eslint/eslint/issues/1494#issuecomment-64246518) to remove the `unused-var` linting rule. I would also suggest to remove auto-fixing the lint errors on commit and instead just report the errors/block commits unless user passes `--no-verify` flag.

**Comment by dadiorchen** [comment]
@kparikh9 I think we can remove `unused-var` but keep the autofix there, is it okay?

**Comment by dadiorchen** [comment]
And do you think rename variable name `next` to `_next` bypassed the problem?

**Comment by kparikh9** [comment]
@dadiorchen yes, I was able to update `.eslintrc` to ignore variables that begin with `_`. Hopefully that rule is ok. Keeping autofix is ok but may lead to varying results/breaking changes such as removing unused variables. Projects I have been a part of typically run `eslint . --cache` in the pre-hook and will block the commit if there are errors. This allows the developer to either run `eslint . --cache --fix`, fix each lint error manually, or run `--no-verify` if the lint errors are not found in code that they wrote. I think this way avoids changes being made to code after it has been committed, but I don't think autofix will usually cause problems like this.

**Comment by kparikh9** [comment]
@dadiorchen I see that the GitHub action is failing on the `npm run tests-e2e` step due to missing environment variables. I think you may have to add `DATABASE_URL` to the Action Secrets of this repo.

**Pull request merged**
