### PR TITLE
Feat/planter order by

### LINKED ISSUE #242: Get /planters support `orderby`
We need to order by `about` for planter list, so please add `order_by=[column name]` in the query parameters. So we can do: `/planters?organization_id=${organization.id}&order_by=about&limit=20&offset=0`.

Ideally, we can order by any possible column, like: created at, name, and so on.

### PR DESCRIPTION
**Pull request by Mohmn**
fixes #242

### CODE REVIEW

**Comment by Mohmn** [comment]
@dadiorchen i have done some refactoring in codebase to support order_by in the firlterOptions and
order_by can be specified by 'columnName:direction'  in the query param , if u r ok with this approach i will do the same thing in other places too

**Comment by dadiorchen** [comment]
Supper! Thanks! 
Just one thing, can you change the URL parameter for order by to follow these:

https://github.com/Greenstand/treetracker-query-api/blob/c50571bd5758af74399de6b1cd2e0bfc0eb0583f/server/routers/capturesRouter.ts#L30-L31

https://github.com/Greenstand/treetracker-api/blob/9ff31dcbe2f027c0aa5bc09a572c70e1ab3562d3/server/handlers/captureHandler/schemas.js#L44

Because we have done these, so to be consistent is better for both coder and user.

**Comment by Mohmn** [comment]
> Supper! Thanks! 
> Just one thing, can you change the URL parameter for order by to follow these:
> 
> https://github.com/Greenstand/treetracker-query-api/blob/c50571bd5758af74399de6b1cd2e0bfc0eb0583f/server/routers/capturesRouter.ts#L30-L31
> 
> https://github.com/Greenstand/treetracker-api/blob/9ff31dcbe2f027c0aa5bc09a572c70e1ab3562d3/server/handlers/captureHandler/schemas.js#L44
> 
> Because we have done these, so to be consistent is better for both coder and user.

Why is it still on hold

**Comment by dadiorchen** [comment]
@Mohmn I missed the notification somehow

**Pull request merged**
