### PR TITLE
fix: chaged the records limit to 100

### PR DESCRIPTION
**Pull request by kunalznk**
I haven't changed limit in capture routes which is 20000 to 100

### CODE REVIEW

**Comment by jeremydthomas** [comment]
fixes #290

**Comment by dadiorchen** [comment]
@kunalznk thank you for you contribution!

**Comment by kunalznk** [comment]
Always welcome @dadiorchen

**Comment by dadiorchen** [comment]
@kunalznk to the requirements of one of our partner, we will give the query API a month time to allow 1000 per page, so now I will revert this PR and restore it a month later

**Pull request merged**
