### PR TITLE
chore: remove explicit 'any' types

### PR DESCRIPTION
**Pull request by QuaidBartolomei**
A good alternative to using `any` is the `unknown` type https://stackoverflow.com/a/51439876/16777502

### CODE REVIEW

**Comment by dadiorchen** [comment]
@QuaidBartolomei if there is a circular reference as you said in the model and repository, what's the problem it leading to?

**Comment by QuaidBartolomei** [comment]
@dadiorchen The circular reference will not necessarily cause errors, but based on my research it can cause hard to find bugs that end up wasting a lot of time.

**Comment by QuaidBartolomei** [comment]
I removed the e2e tests from the workflow. They were not working because PRs from forked repos do not have access to github repo secrets.

**Comment by dadiorchen** [comment]
Thanks @QuaidBartolomei

**Pull request merged**
