### PR TITLE
Added country & continent for planter filter

### LINKED ISSUE #184: The GET /planters api do not return country, continent info
https://prod-k8s.treetracker.org/query/planters?organization_id=775&limit=20&offset=0
should return: 
country_id
country_name
continent_id
continent_name

### PR DESCRIPTION
**Pull request by mayankbucha**
resolves #184

### CODE REVIEW

**Comment by mayankbucha** [comment]
@dadiorchen, here to get the country of planter I have joined `planter.id on locations.planter_id` and converted lat and lon to `POINT(4326)` and on that point I have run query to get country and continent.


It is bit different from the pervious logic where we have used `trees` table `trees.estimated_geometric_location` get the country and continent. Here I felt that tress can be anywhere and they don't necessarily represent planter location, hence I haven't used this logic and went ahead with locations table.


So, will this logic be fine as both are giving different results?

**Comment by dadiorchen** [comment]
@mayankbucha sorry for the choas, the `locations` is not used, so, the logic to get the planter's location is, get tree's location by that planter, and because we don't have crossing-country planter, so we use this to locate the planter, in furuture's android app, we will fetch the planter's GPS location to fill in the table, so to get a more accurate result on this, but now, we can not do it.

**Comment by mayankbucha** [comment]
@dadiorchen above commit is returning duplicate records, I cannot figure out why it is happening. This is the query `/planters?organization_id=15`  which is returning duplicate records of same planter.

**Comment by dadiorchen** [comment]
@mayankbucha so if I download your branch, fix-184, I can reproduce this problem right? Okay, I will fetch you code and take a look

**Pull request merged**
