### PR TITLE
feat: added support tag query parameter for the endpoint /trees?

### LINKED ISSUE #52: the tree list API support: /trees?tag=[tag_name]
Now we already have: /trees? 
We need to make it support the query parameter: tag=[tag_name], the tag name was set in the admin panel as shown in the picture below.

Screen Shot 2022-01-20 at 5 21 03 PM

There is a tag table to support this feature, please ask me on slack if you don't understand the data table structure. 

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

### PR DESCRIPTION
**Pull request by Mohmn**
resolves #52

### CODE REVIEW

**Comment by dadiorchen** [comment]
@Mohmn thanks for the contribution, there are some problems in this PR:
1. Don't need to modify version number and changelog manually, we use release bot for this: https://www.npmjs.com/~semantic-release-bot
2. The way we develop is that first, write the test to cover the target API, then implement it, so I didn't see your test covering the API?

**Comment by Mohmn** [comment]
@dadiorchen I didn't modify the version number and changelog, don't know how these files changed
since there wasn't any Trees.spce.ts file, I thought that tests are not required for this endpoint
I will be writing the test case for the endpoint

**Comment by dadiorchen** [comment]
@Mohmn can you roll back the change on files: CHANGELOG.md package.json?

**Comment by Mohmn** [comment]
@dadiorchen  done please check

**Review by dadiorchen — APPROVED** [review]

**Comment by dadiorchen** [comment]
Looks good to me, @dagmawig could you review this?

**Review by dagmawig — APPROVED** [review]
Looks good to me.

**Pull request merged**
