### PR TITLE
feat: endpoint get/tree/ now returns organization_id and organization…

### LINKED ISSUE #105: Get /trees/id : return organization_id and organization_name
Extend the GET /trees/:id endpoint to return organization id and name.

This requires extra `join` to get the org info from `entity` table

### PR DESCRIPTION
**Pull request by Mohmn**
Screenshot from 2022-05-25 00-24-19
…_name

resolves #105

### CODE REVIEW

**Comment by dadiorchen** [comment]
@Mohmn super! Thanks for the contribution! btw, if you want I can invite you to our slack community by your email adress.

**Review by dadiorchen — APPROVED** [review]

**Comment by Mohmn** [comment]
@dadiorchen you have already added me on slack

**Comment by dadiorchen** [comment]
@dagmawig can you review this?

**Review by dagmawig — APPROVED** [review]
It looks good! Returns the org name and id as expected under which a specific tree is planted.

**Comment by dadiorchen** [comment]
@Mohmn oh, could you please fix these conflict, I guess this is caused by newest merge.

**Comment by Mohmn** [comment]
@dadiorchen merged

**Comment by dadiorchen** [comment]
@Mohmn thank you!

**Pull request merged**
